create database amazon;
use amazon;
select count(*) from products;

-- 1. Query the top 10 products by total sales value, including product name,
-- total quantity sold, and total sales value.
select p.product_name,
sum(o.quantity) as total_quantity_sold,
round(sum(quantity * price_per_unit),2) as total_sales from products p
join order_items o on p.product_id = o.product_id
group by p.product_name
order by total_sales desc limit 10;



-- 2. Calculate total revenue generated by each product category and include
-- the percentage contribution of each category to total revenue.

SELECT 
  c.category_name,
  ROUND(SUM(oi.quantity * oi.price_per_unit), 2) AS category_revenue,
  ROUND(
    SUM(oi.quantity * oi.price_per_unit) * 100.0 / 
    (SELECT SUM(quantity * price_per_unit) FROM order_items),
    2
  ) AS revenue_percentage
FROM products p
JOIN category c ON p.category_id = c.category_id
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY category_revenue DESC;


-- 3. Compute the average order value (AOV) for each customer and include
-- only customers with more than 5 orders.
SELECT 
c.customer_id,
c.first_name,
c.last_name,
COUNT(DISTINCT o.order_id) AS total_orders,
ROUND(SUM(oi.quantity * oi.price_per_unit) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING COUNT(DISTINCT o.order_id) > 5
ORDER BY avg_order_value DESC;

-- 4. Query monthly total sales over the past year and display the current
-- month’s sales along with the previous month’s sales.
WITH monthly_sales AS (
  SELECT
    DATE_FORMAT(o.order_date, '%Y-%m-01') AS month_start,
    SUM(oi.quantity * oi.price_per_unit) AS month_sales
  FROM orders o
  JOIN order_items oi ON oi.order_id = o.order_id
  WHERE o.order_date >= (
    SELECT DATE_SUB(MAX(order_date), INTERVAL 1 YEAR) FROM orders
  )
  GROUP BY DATE_FORMAT(o.order_date, '%Y-%m-01')
)
SELECT
  cur.month_start AS month,
  cur.month_sales AS current_month_sales,
  prev.month_sales AS previous_month_sales
FROM monthly_sales cur
LEFT JOIN monthly_sales prev
  ON prev.month_start = DATE_FORMAT(
       DATE_SUB(cur.month_start, INTERVAL 1 MONTH),
       '%Y-%m-01'
     )
ORDER BY cur.month_start;

-- 5. Find customers who have registered but never placed an order, listing
-- customer details and the time since their registration.

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.state
FROM customers AS c
LEFT JOIN orders AS o
    ON o.customer_id = c.customer_id
WHERE
    o.order_id IS NULL;

-- 6. Identify the least-selling product category for each state and include the
-- total sales for that category within each state.
WITH category_sales AS (
    SELECT 
        c.state,
        cat.category_name,
        SUM(oi.quantity * oi.price_per_unit) AS total_sales
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN products p ON oi.product_id = p.product_id
    JOIN category cat ON p.category_id = cat.category_id
    GROUP BY c.state, cat.category_name
)
SELECT state, category_name, total_sales
FROM (
    SELECT 
        state,
        category_name,
        total_sales,
        RANK() OVER (PARTITION BY state ORDER BY total_sales ASC) AS sales_rank
    FROM category_sales
) ranked_sales
WHERE sales_rank = 1
ORDER BY state;


-- 7. Calculate the customer lifetime value (CLTV) for each customer and
-- rank customers based on their CLTV.
SELECT 
c.customer_id,
c.first_name,
c.last_name,
ROUND(SUM(oi.quantity * oi.price_per_unit), 2) AS cltv,
RANK() OVER (ORDER BY SUM(oi.quantity * oi.price_per_unit) DESC) AS cltv_rank
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY cltv DESC;


-- 8. Query products with stock levels below a certain threshold (e.g., less
-- than 10 units) and include the last restock date and warehouse
-- information.
SELECT 
    p.product_id,
    p.product_name,
    i.stock,
    i.warehouse_id,
    i.last_stock_date
FROM products p
JOIN inventory i ON p.product_id = i.product_id
WHERE i.stock < 10
ORDER BY i.stock ASC;


-- 9. Calculate the percentage of successful payments across all orders and
-- include a breakdown by payment status such as failed and pending.
SELECT 
    payment_status,
    COUNT(*) AS total_payments,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM payments), 2) AS percentage
FROM payments
GROUP BY payment_status
ORDER BY percentage DESC;


-- 10. Query the top 10 products by the number of returns and display the
-- return rate as a percentage of total units sold for each product.

WITH product_sales AS (
    SELECT 
        p.product_id,
        p.product_name,
        SUM(oi.quantity) AS total_units_sold
    FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    GROUP BY p.product_id, p.product_name
),
product_returns AS (
    SELECT 
        p.product_id,
        COUNT(*) AS total_returns
    FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    JOIN shipping s ON oi.order_id = s.order_id
    WHERE s.return_date IS NOT NULL
    GROUP BY p.product_id
)
SELECT 
    ps.product_name,
    ps.total_units_sold,
    COALESCE(pr.total_returns, 0) AS total_returns,
    ROUND(COALESCE(pr.total_returns, 0) * 100.0 / ps.total_units_sold, 2) AS return_rate_percentage
FROM product_sales ps
LEFT JOIN product_returns pr ON ps.product_id = pr.product_id
ORDER BY total_returns DESC
LIMIT 10;